function dkb = fdkb(in1,in2)
%FDKB
%    DKB = FDKB(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    27-Oct-2017 12:40:40

a1 = in1(:,1);
a2 = in1(:,2);
a3 = in1(:,3);
b1 = in2(:,1);
b2 = in2(:,2);
b3 = in2(:,3);
t2 = a1-b1;
t3 = a2-b2;
t4 = a3-b3;
t5 = t2.^2;
t6 = t3.^2;
t7 = t4.^2;
t8 = t5+t6+t7+1.0;
t9 = 1.0./t8.^(3.0./2.0);
dkb = [t9.*(a1.*2.0-b1.*2.0).*(1.0./2.0),t9.*(a2.*2.0-b2.*2.0).*(1.0./2.0),t9.*(a3.*2.0-b3.*2.0).*(1.0./2.0)];
