function k = fk(in1,in2)
%FK
%    K = FK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    27-Oct-2017 12:40:40

a1 = in1(:,1);
a2 = in1(:,2);
a3 = in1(:,3);
b1 = in2(:,1);
b2 = in2(:,2);
b3 = in2(:,3);
t2 = a1-b1;
t3 = a2-b2;
t4 = a3-b3;
k = 1.0./sqrt(t2.^2+t3.^2+t4.^2+1.0);
